import Foundation

public enum Action: String, Codable {
  case all = "*"
  case search = "search"
  case allDocuments = "documents.*"
  case addDocuments = "documents.add"
  case getDocuments = "documents.get"
  case deleteDocuments = "documents.delete"
  case allIndexes = "indexes.*"
  case createIndexes = "indexes.create"
  case getIndexes = "indexes.get"
  case updateIndexes = "indexes.update"
  case deleteIndexes = "indexes.delete"
  case swapIndexes = "indexes.swap"
  case allTasks = "tasks.*"
  case getTasks = "tasks.get"
  case cancelTasks = "tasks.cancel"
  case deleteTasks = "tasks.delete"
  case allSettings = "settings.*"
  case getSettings = "settings.get"
  case updateSettings = "settings.update"
  case getStats = "stats.get"
  case createDumps = "dumps.create"
  case getDumps = "dumps.get"
  case allKeys = "key.*"
  case getKeys = "key.get"
  case createKeys = "key.create"
  case updateKeys = "key.update"
  case deleteKeys = "key.delete"
  case version = "version"
}
